openapi: 3.0.3
info:
  title: 'Google Drive Clone API'
  description: "Our API provides comprehensive functionality for managing files and folders in a cloud storage environment, akin to Google Drive. Built with Laravel, it offers robust endpoints for seamless integration with your front-end applications. With secure authentication mechanisms and efficient data handling, our API enables users to upload, download, organize, and share files effortlessly. Whether you're building a personal file repository or a collaborative workspace, our API empowers you to create a powerful cloud storage solution tailored to your needs."
  version: 1.0.0
servers:
  -
    url: 'https://google-drive-clone-api.wip'
paths:
  /api/v1/register:
    post:
      summary: 'Register a new user.'
      operationId: registerANewUser
      description: 'Registers a user based on the provided registration request'
      parameters:
        -
          in: header
          name: Accept-Language
          description: ''
          example: en
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 15
                    name: 'Nannie Hintz'
                    email: lolita.gutkowski@example.com
                    created_at:
                      datetime: '2024-04-05T20:40:48.000000Z'
                      human_diff: '0 seconds ago'
                      human: 'Fri, Apr 5, 2024 8:40 PM'
                  token: 1|Ue8Wpv3izBua27OmZAAmk8eofN7XS7iQSzyiLW7c1f96270e
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 15
                      name:
                        type: string
                        example: 'Nannie Hintz'
                      email:
                        type: string
                        example: lolita.gutkowski@example.com
                      created_at:
                        type: object
                        properties:
                          datetime:
                            type: string
                            example: '2024-04-05T20:40:48.000000Z'
                          human_diff:
                            type: string
                            example: '0 seconds ago'
                          human:
                            type: string
                            example: 'Fri, Apr 5, 2024 8:40 PM'
                  token:
                    type: string
                    example: 1|Ue8Wpv3izBua27OmZAAmk8eofN7XS7iQSzyiLW7c1f96270e
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: 'User name. Must not be greater than 255 characters.'
                  example: 'John Doe'
                email:
                  type: string
                  description: 'User email. Must be a valid email address. Must not be greater than 255 characters.'
                  example: john.doe@example.com
                password:
                  type: string
                  description: 'User password.'
                  example: password
                password_confirmation:
                  type: string
                  description: 'User password confirmation.'
                  example: password
              required:
                - name
                - email
                - password
                - password_confirmation
      security: []
  /api/v1/login:
    post:
      summary: 'Login a user'
      operationId: loginAUser
      description: 'Logins a user based on the provided login request'
      parameters:
        -
          in: header
          name: Accept-Language
          description: ''
          example: en
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 16
                    name: 'Kasandra Rempel'
                    email: bennett79@example.net
                    created_at:
                      datetime: '2024-04-05T20:40:49.000000Z'
                      human_diff: '0 seconds ago'
                      human: 'Fri, Apr 5, 2024 8:40 PM'
                  token: 1|Ue8Wpv3izBua27OmZAAmk8eofN7XS7iQSzyiLW7c1f96270e
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 16
                      name:
                        type: string
                        example: 'Kasandra Rempel'
                      email:
                        type: string
                        example: bennett79@example.net
                      created_at:
                        type: object
                        properties:
                          datetime:
                            type: string
                            example: '2024-04-05T20:40:49.000000Z'
                          human_diff:
                            type: string
                            example: '0 seconds ago'
                          human:
                            type: string
                            example: 'Fri, Apr 5, 2024 8:40 PM'
                  token:
                    type: string
                    example: 1|Ue8Wpv3izBua27OmZAAmk8eofN7XS7iQSzyiLW7c1f96270e
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'User email. Must be a valid email address.'
                  example: john.doe@example.com
                password:
                  type: string
                  description: 'User password.'
                  example: password
              required:
                - email
                - password
      security: []
  /api/v1/password/email:
    post:
      summary: 'Password reset link.'
      operationId: passwordResetLink
      description: 'Send a reset link to the given user.'
      parameters:
        -
          in: header
          name: Accept-Language
          description: ''
          example: en
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'We have e-mailed your password reset link.'
                properties:
                  message:
                    type: string
                    example: 'We have e-mailed your password reset link.'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'User email. Must be a valid email address.'
                  example: john.doe@example.com
              required:
                - email
  /api/v1/password/reset:
    post:
      summary: 'Reset password.'
      operationId: resetPassword
      description: "Reset the given user's password."
      parameters:
        -
          in: header
          name: Accept-Language
          description: ''
          example: en
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Your password has been reset.'
                properties:
                  message:
                    type: string
                    example: 'Your password has been reset.'
      tags:
        - Authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                token:
                  type: string
                  description: 'The reset password token.'
                  example: quaerat
                email:
                  type: string
                  description: 'The email address. Must be a valid email address.'
                  example: hope.gutkowski@example.net
                password:
                  type: string
                  description: 'The new password.'
                  example: '~(KvUyeGV.s&'
                password_confirmation:
                  type: string
                  description: 'The password confirmation.'
                  example: aspernatur
              required:
                - token
                - email
                - password
                - password_confirmation
      security: []
  '/api/v1/email/verify/{id}/{hash}':
    get:
      summary: 'Verify email'
      operationId: verifyEmail
      description: 'Verify the email of the user.'
      parameters:
        -
          in: header
          name: Accept-Language
          description: ''
          example: en
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Email successfully verified'
                properties:
                  message:
                    type: string
                    example: 'Email successfully verified'
      tags:
        - Authentication
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the user.'
        example: '1'
        required: true
        schema:
          type: string
      -
        in: path
        name: hash
        description: 'The hash of the user.'
        example: 56Z83cdafEvb1P4VheDga6k
        required: true
        schema:
          type: string
  /api/v1/email/resend:
    post:
      summary: 'Resend email'
      operationId: resendEmail
      description: 'Resend the email verification notification.'
      parameters:
        -
          in: header
          name: Accept-Language
          description: ''
          example: en
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Email verification link sent on your email id'
                properties:
                  message:
                    type: string
                    example: 'Email verification link sent on your email id'
      tags:
        - Authentication
      security: []
  /api/v1/logout:
    post:
      summary: 'Signs out a user'
      operationId: signsOutAUser
      description: ''
      parameters:
        -
          in: header
          name: Accept-Language
          description: ''
          example: en
          schema:
            type: string
      responses:
        204:
          description: ''
      tags:
        - Authentication
  /api/v1/user:
    get:
      summary: 'Current user'
      operationId: currentUser
      description: 'Get the currently authenticated user.'
      parameters:
        -
          in: header
          name: Accept-Language
          description: ''
          example: en
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 23
                    name: 'Lillie Sipes'
                    email: serena79@example.com
                    created_at:
                      datetime: '2024-04-05T20:40:53.000000Z'
                      human_diff: '0 seconds ago'
                      human: 'Fri, Apr 5, 2024 8:40 PM'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 23
                      name:
                        type: string
                        example: 'Lillie Sipes'
                      email:
                        type: string
                        example: serena79@example.com
                      created_at:
                        type: object
                        properties:
                          datetime:
                            type: string
                            example: '2024-04-05T20:40:53.000000Z'
                          human_diff:
                            type: string
                            example: '0 seconds ago'
                          human:
                            type: string
                            example: 'Fri, Apr 5, 2024 8:40 PM'
      tags:
        - Authentication
  /api/v1/folders:
    post:
      summary: 'Create folder'
      operationId: createFolder
      description: 'Store a newly created folder.'
      parameters:
        -
          in: header
          name: Accept-Language
          description: ''
          example: en
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 5
                    name: 'Whitney Parisian'
                    path: 'http://yundt.info/aut-et-et-culpa-repudiandae-assumenda-rerum-repudiandae-est.html'
                    storage_path: 'http://farrell.com/'
                    parent_id: null
                    lft: 1
                    rgt: 2
                    depth: 0
                    is_folder: true
                    mime: application/xv+xml
                    size: '430.83 KB'
                    owner: 'Prof. Vivienne Rau IV'
                    uploaded_on_cloud: false
                    created_by:
                      id: 17
                      name: 'Prof. Vivienne Rau IV'
                      email: raynor.nedra@example.org
                      created_at:
                        datetime: '2024-04-05T20:40:50.000000Z'
                        human_diff: '0 seconds ago'
                        human: 'Fri, Apr 5, 2024 8:40 PM'
                    created_at:
                      datetime: '2024-04-05T20:40:50.000000Z'
                      human_diff: '0 seconds ago'
                      human: 'Fri, Apr 5, 2024 8:40 PM'
                    updated_at:
                      datetime: '2024-04-05T20:40:50.000000Z'
                      human_diff: '0 seconds ago'
                      human: 'Fri, Apr 5, 2024 8:40 PM'
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                        example: 5
                      name:
                        type: string
                        example: 'Whitney Parisian'
                      path:
                        type: string
                        example: 'http://yundt.info/aut-et-et-culpa-repudiandae-assumenda-rerum-repudiandae-est.html'
                      storage_path:
                        type: string
                        example: 'http://farrell.com/'
                      parent_id:
                        type: string
                        example: null
                      lft:
                        type: integer
                        example: 1
                      rgt:
                        type: integer
                        example: 2
                      depth:
                        type: integer
                        example: 0
                      is_folder:
                        type: boolean
                        example: true
                      mime:
                        type: string
                        example: application/xv+xml
                      size:
                        type: string
                        example: '430.83 KB'
                      owner:
                        type: string
                        example: 'Prof. Vivienne Rau IV'
                      uploaded_on_cloud:
                        type: boolean
                        example: false
                      created_by:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 17
                          name:
                            type: string
                            example: 'Prof. Vivienne Rau IV'
                          email:
                            type: string
                            example: raynor.nedra@example.org
                          created_at:
                            type: object
                            properties:
                              datetime:
                                type: string
                                example: '2024-04-05T20:40:50.000000Z'
                              human_diff:
                                type: string
                                example: '0 seconds ago'
                              human:
                                type: string
                                example: 'Fri, Apr 5, 2024 8:40 PM'
                      created_at:
                        type: object
                        properties:
                          datetime:
                            type: string
                            example: '2024-04-05T20:40:50.000000Z'
                          human_diff:
                            type: string
                            example: '0 seconds ago'
                          human:
                            type: string
                            example: 'Fri, Apr 5, 2024 8:40 PM'
                      updated_at:
                        type: object
                        properties:
                          datetime:
                            type: string
                            example: '2024-04-05T20:40:50.000000Z'
                          human_diff:
                            type: string
                            example: '0 seconds ago'
                          human:
                            type: string
                            example: 'Fri, Apr 5, 2024 8:40 PM'
      tags:
        - 'Files Management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                parent_id:
                  type: string
                  description: 'The ID of the parent folder.'
                  example: '1'
                name:
                  type: string
                  description: 'The name of the folder. Must not be greater than 1024 characters.'
                  example: ddf
              required:
                - parent_id
                - name
  '/api/v1/files/{folder}':
    get:
      summary: 'User files'
      operationId: userFiles
      description: 'Get the current user files.'
      parameters:
        -
          in: header
          name: Accept-Language
          description: ''
          example: en
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    -
                      id: 6
                      name: 'Jadon Armstrong'
                      path: 'http://paucek.com/'
                      storage_path: 'http://monahan.com/odit-doloremque-quia-animi-laborum-sed'
                      parent_id: null
                      lft: 1
                      rgt: 2
                      depth: 0
                      is_folder: false
                      mime: video/vnd.ms-playready.media.pyv
                      size: '517.84 KB'
                      owner: 'Dortha Zboncak'
                      uploaded_on_cloud: true
                      created_by:
                        id: 19
                        name: 'Dortha Zboncak'
                        email: dlegros@example.net
                        created_at:
                          datetime: '2024-04-05T20:40:51.000000Z'
                          human_diff: '2 seconds ago'
                          human: 'Fri, Apr 5, 2024 8:40 PM'
                      created_at:
                        datetime: '2024-04-05T20:40:51.000000Z'
                        human_diff: '2 seconds ago'
                        human: 'Fri, Apr 5, 2024 8:40 PM'
                      updated_at:
                        datetime: '2024-04-05T20:40:51.000000Z'
                        human_diff: '2 seconds ago'
                        human: 'Fri, Apr 5, 2024 8:40 PM'
                    -
                      id: 7
                      name: 'Kiana Graham'
                      path: 'http://www.dickens.info/laudantium-enim-molestiae-placeat-harum-in-modi-error.html'
                      storage_path: 'http://www.bernhard.com/'
                      parent_id: null
                      lft: 3
                      rgt: 4
                      depth: 0
                      is_folder: true
                      mime: application/vnd.ms-wpl
                      size: '858.59 KB'
                      owner: 'Lucie Davis'
                      uploaded_on_cloud: true
                      created_by:
                        id: 21
                        name: 'Lucie Davis'
                        email: dbrown@example.net
                        created_at:
                          datetime: '2024-04-05T20:40:52.000000Z'
                          human_diff: '1 second ago'
                          human: 'Fri, Apr 5, 2024 8:40 PM'
                      created_at:
                        datetime: '2024-04-05T20:40:53.000000Z'
                        human_diff: '0 seconds ago'
                        human: 'Fri, Apr 5, 2024 8:40 PM'
                      updated_at:
                        datetime: '2024-04-05T20:40:53.000000Z'
                        human_diff: '0 seconds ago'
                        human: 'Fri, Apr 5, 2024 8:40 PM'
                properties:
                  data:
                    type: array
                    example:
                      -
                        id: 6
                        name: 'Jadon Armstrong'
                        path: 'http://paucek.com/'
                        storage_path: 'http://monahan.com/odit-doloremque-quia-animi-laborum-sed'
                        parent_id: null
                        lft: 1
                        rgt: 2
                        depth: 0
                        is_folder: false
                        mime: video/vnd.ms-playready.media.pyv
                        size: '517.84 KB'
                        owner: 'Dortha Zboncak'
                        uploaded_on_cloud: true
                        created_by:
                          id: 19
                          name: 'Dortha Zboncak'
                          email: dlegros@example.net
                          created_at:
                            datetime: '2024-04-05T20:40:51.000000Z'
                            human_diff: '2 seconds ago'
                            human: 'Fri, Apr 5, 2024 8:40 PM'
                        created_at:
                          datetime: '2024-04-05T20:40:51.000000Z'
                          human_diff: '2 seconds ago'
                          human: 'Fri, Apr 5, 2024 8:40 PM'
                        updated_at:
                          datetime: '2024-04-05T20:40:51.000000Z'
                          human_diff: '2 seconds ago'
                          human: 'Fri, Apr 5, 2024 8:40 PM'
                      -
                        id: 7
                        name: 'Kiana Graham'
                        path: 'http://www.dickens.info/laudantium-enim-molestiae-placeat-harum-in-modi-error.html'
                        storage_path: 'http://www.bernhard.com/'
                        parent_id: null
                        lft: 3
                        rgt: 4
                        depth: 0
                        is_folder: true
                        mime: application/vnd.ms-wpl
                        size: '858.59 KB'
                        owner: 'Lucie Davis'
                        uploaded_on_cloud: true
                        created_by:
                          id: 21
                          name: 'Lucie Davis'
                          email: dbrown@example.net
                          created_at:
                            datetime: '2024-04-05T20:40:52.000000Z'
                            human_diff: '1 second ago'
                            human: 'Fri, Apr 5, 2024 8:40 PM'
                        created_at:
                          datetime: '2024-04-05T20:40:53.000000Z'
                          human_diff: '0 seconds ago'
                          human: 'Fri, Apr 5, 2024 8:40 PM'
                        updated_at:
                          datetime: '2024-04-05T20:40:53.000000Z'
                          human_diff: '0 seconds ago'
                          human: 'Fri, Apr 5, 2024 8:40 PM'
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          example: 6
                        name:
                          type: string
                          example: 'Jadon Armstrong'
                        path:
                          type: string
                          example: 'http://paucek.com/'
                        storage_path:
                          type: string
                          example: 'http://monahan.com/odit-doloremque-quia-animi-laborum-sed'
                        parent_id:
                          type: string
                          example: null
                        lft:
                          type: integer
                          example: 1
                        rgt:
                          type: integer
                          example: 2
                        depth:
                          type: integer
                          example: 0
                        is_folder:
                          type: boolean
                          example: false
                        mime:
                          type: string
                          example: video/vnd.ms-playready.media.pyv
                        size:
                          type: string
                          example: '517.84 KB'
                        owner:
                          type: string
                          example: 'Dortha Zboncak'
                        uploaded_on_cloud:
                          type: boolean
                          example: true
                        created_by:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 19
                            name:
                              type: string
                              example: 'Dortha Zboncak'
                            email:
                              type: string
                              example: dlegros@example.net
                            created_at:
                              type: object
                              properties:
                                datetime:
                                  type: string
                                  example: '2024-04-05T20:40:51.000000Z'
                                human_diff:
                                  type: string
                                  example: '2 seconds ago'
                                human:
                                  type: string
                                  example: 'Fri, Apr 5, 2024 8:40 PM'
                        created_at:
                          type: object
                          properties:
                            datetime:
                              type: string
                              example: '2024-04-05T20:40:51.000000Z'
                            human_diff:
                              type: string
                              example: '2 seconds ago'
                            human:
                              type: string
                              example: 'Fri, Apr 5, 2024 8:40 PM'
                        updated_at:
                          type: object
                          properties:
                            datetime:
                              type: string
                              example: '2024-04-05T20:40:51.000000Z'
                            human_diff:
                              type: string
                              example: '2 seconds ago'
                            human:
                              type: string
                              example: 'Fri, Apr 5, 2024 8:40 PM'
      tags:
        - 'Files Management'
    parameters:
      -
        in: path
        name: folder
        description: 'Optional parameter. The path of the folder.'
        required: true
        schema:
          type: string
        examples:
          omitted:
            summary: 'When the value is omitted'
            value: ''
          present:
            summary: 'When the value is present'
            value: documents
      -
        in: path
        name: perPage
        description: 'Optional parameter. The number of files per page.'
        required: true
        schema:
          type: integer
        examples:
          omitted:
            summary: 'When the value is omitted'
            value: ''
          present:
            summary: 'When the value is present'
            value: 15
      -
        in: path
        name: page
        description: 'Optional parameter. The page number.'
        required: true
        schema:
          type: integer
        examples:
          omitted:
            summary: 'When the value is omitted'
            value: ''
          present:
            summary: 'When the value is present'
            value: 1
  /api/v1/files:
    post:
      summary: ''
      operationId: postApiV1Files
      description: ''
      parameters: []
      responses: {  }
      tags:
        - 'Files Management'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                parent_id:
                  type: string
                  description: 'The ID of the parent folder.'
                  example: '1'
                folder_name:
                  type: string
                  description: ''
                  example: fugit
                files:
                  type: array
                  description: 'The file to upload. Must be a file.'
                  items:
                    type: string
                    format: binary
              required:
                - parent_id
                - files
tags:
  -
    name: Authentication
    description: "\nAPIs for authentication"
  -
    name: 'Files Management'
    description: "\nAPIs for managing users files"
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
